"""empty message

Revision ID: 43d84101f808
Revises: 89e755497b8e
Create Date: 2024-01-14 16:57:40.295708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d84101f808'
down_revision = '89e755497b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_readonly_name', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('has_readonly_name')

    # ### end Alembic commands ###
