"""empty message

Revision ID: 89e755497b8e
Revises: 86ce6a126c32
Create Date: 2024-01-13 21:12:33.551115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e755497b8e'
down_revision = '86ce6a126c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_alembic_tmp_notes")
    table_name = sa.sql.table(
        "notes", sa.Column("password", sa.VARCHAR()), schema=None
    )
    op.execute(
        table_name.update()
        .where(table_name.c.password.is_(None))
        .values(password="")
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               server_default="",
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('_alembic_tmp_notes',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('clip_version', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('readonly_name', sa.VARCHAR(), nullable=False),
    sa.Column('timeout_seconds', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('all_file_size', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('readonly_name')
    )
    # ### end Alembic commands ###
