"""empty message

Revision ID: a1f0499a631d
Revises: 8cb40c637de8
Create Date: 2024-01-11 18:09:01.979113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1f0499a631d"
down_revision = "8cb40c637de8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "all_file_size",
                sa.Integer(),
                nullable=False,
                default=0,
                server_default=sa.sql.expression.literal(0),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_column("all_file_size")

    # ### end Alembic commands ###
