"""empty message

Revision ID: c3026b515bcc
Revises: 5bcdee6dfe86
Create Date: 2024-07-08 21:03:28.153360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3026b515bcc'
down_revision = '5bcdee6dfe86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_property', sa.String(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('user_property')

    # ### end Alembic commands ###
